/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto_gerenciamento;

import modelo.DAO;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

/**
 *
 * @author danim
 */
public class interface_gerenciamento extends javax.swing.JFrame {
    private DAO funcao;

    /**
     * Creates new form interface_gerenciamento
     */
    public interface_gerenciamento() {
        initComponents();
        funcao = new DAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaResultados = new javax.swing.JTextArea();
        lblFeicash = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        lblCampo = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        btnSaldo = new javax.swing.JButton();
        btnExtratoCashback = new javax.swing.JButton();
        btnExtratoNotas = new javax.swing.JButton();
        btnMostrarTodos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaResultados.setColumns(20);
        areaResultados.setRows(5);
        jScrollPane1.setViewportView(areaResultados);

        lblFeicash.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFeicash.setForeground(new java.awt.Color(0, 0, 240));
        lblFeicash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFeicash.setText("FEICASH");
        lblFeicash.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 240)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCpf.setText("CPF:");

        lblCampo.setText("Campo de busca de clientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCpf))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblCampo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblCampo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnExcluir.setBackground(new java.awt.Color(240, 0, 0));
        btnExcluir.setText("Excluir ");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSaldo.setText("Saldo");
        btnSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoActionPerformed(evt);
            }
        });

        btnExtratoCashback.setText("Extrato CashBack ");
        btnExtratoCashback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtratoCashbackActionPerformed(evt);
            }
        });

        btnExtratoNotas.setText("Extrato notas");
        btnExtratoNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtratoNotasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnExtratoCashback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExtratoNotas, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExtratoCashback, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(btnExtratoNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnMostrarTodos.setText("Mostrar Todos");
        btnMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(240, 0, 0));
        jButton1.setText("sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(lblFeicash, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFeicash, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnMostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        String cpf = txtCpf.getText();
        
        String status = funcao.excluirCadastro(cpf);
        String status2 = funcao.excluirCadastro_nf(cpf);
        
        
        if(!cpf.equals("")){
            if(status == "ok" && status2 == "ok"){
                String s = "Cliente removido com sucesso do FEICASH.";
                JOptionPane.showMessageDialog(null, s, "Informação: Usuário removido.", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                String s = status;
                JOptionPane.showMessageDialog(null, s, "Erro na remoção", JOptionPane.ERROR_MESSAGE);

            }
        }
        else{
            String s = "CPF inexistente";
            JOptionPane.showMessageDialog(null, s, "Erro na remoção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed
        try {
            ResultSet rs = funcao.exibirTodas();
            String lista = "";
            while (rs.next()) {
                lista = lista + "NOME: " + rs.getString("NOME") + "\t\tCPF: " + rs.getString("CPF") +"\n";
            }
            areaResultados.setText(lista);
            String s = "Todos os clientes carregados com Sucesso!";
            JOptionPane.showMessageDialog(null, s, "Informação: Lista Carregada.", JOptionPane.INFORMATION_MESSAGE);
            
        } catch( SQLException e) {
            String s = "Consulta não foi possível" + e.getMessage();
            JOptionPane.showMessageDialog(null, s, "Erro na busca", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    private void btnExtratoCashbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtratoCashbackActionPerformed
        String cpf = txtCpf.getText();
        boolean encontrou = funcao.buscarCpf(cpf);
        if(encontrou){
            try {
                ResultSet rs2 = funcao.buscarInfosClientes(cpf);
                String lista = "";
                while (rs2.next()) {
                    lista = "NOME: " + rs2.getString("NOME") + "\nCPF: " + rs2.getString("CPF") + "\nSALDO ATUAL: R$ " + String.format("%.2f", rs2.getDouble("SALDO"))+"\n";
                }


                ResultSet rs = funcao.buscarCashbackPorCPF(cpf);

                while (rs.next()) {
                    lista = lista + "DATA: " + rs.getDate("DATA")+" "+rs.getTime("HORA") + "   " + rs.getString("STATUS")+ "   ";
                    lista = lista + String.format("%.2f", rs.getDouble("CASHBACK")) + "\tSALDO: R$ " + String.format("%.2f", rs.getDouble("SALDO"))+"\n";
                }
                areaResultados.setText(lista);
                String s = "Extrato cashback encontrado!";
                JOptionPane.showMessageDialog(null, s, "Informação: Extrato Carregado.", JOptionPane.INFORMATION_MESSAGE);

            } catch( SQLException e) {
                String s = "Consulta não foi possível " + e.getMessage();
                JOptionPane.showMessageDialog(null, s, "Erro na busca do cliente", JOptionPane.ERROR_MESSAGE);
            }       
        }
        else{
            String s = "Consulta não foi possível, digite um CPF correto.";
            JOptionPane.showMessageDialog(null, s, "Erro na busca do cliente", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExtratoCashbackActionPerformed

    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
        try {
            ResultSet rs = funcao.exibirTodas();
            String lista = "";
            while (rs.next()) {
                lista = lista + "NOME: " + rs.getString("NOME") + "\t\tCPF: " + rs.getString("CPF") + "\tSALDO: R$ " + String.format("%.2f", rs.getDouble("SALDO"))+"\n";
            }
            areaResultados.setText(lista);
            String s = "Todos os clientes carregados com Sucesso!";
            JOptionPane.showMessageDialog(null, s, "Informação: Lista Carregada.", JOptionPane.INFORMATION_MESSAGE);
            
        } catch( SQLException e) {
            String s = "Consulta não foi possível " + e.getMessage();
            JOptionPane.showMessageDialog(null, s, "Erro na busca", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaldoActionPerformed

    private void btnExtratoNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtratoNotasActionPerformed
        String cpf = txtCpf.getText(); 
        boolean encontrou = funcao.buscarCpf(cpf);
        if(encontrou){    
            try {
                ResultSet rs2 = funcao.buscarInfosClientes(cpf);

                String lista = "";
                while (rs2.next()) {
                    lista = "NOME: " + rs2.getString("NOME") + "\nCPF: " + rs2.getString("CPF") 
                    +"\n"+ "Data do Cadastro"+"\tValor da compra (R$)"+"\t%"+"\tCashBack (R$)"+"\t    Compra Online\n";
                }

                ResultSet rs = funcao.buscarNFPorCPF(cpf);
                
                SimpleDateFormat simpDate = new SimpleDateFormat("dd-MM-yyyy");                

                while (rs.next()) {
                    if("Sim".equals(rs.getString("Online"))){
                        lista = lista + simpDate.format(rs.getDate("DATA"))+" "+rs.getTime("HORA") +"\t"+ String.format("%.2f", rs.getDouble("VALOR")) +"\t\t";
                        lista = lista + "5%\t";
                        lista = lista + String.format("%.2f", rs.getDouble("CASHBACK")) + "\t    " + rs.getString("ONLINE") + "\n";
                    }
                    else if ("Não".equals(rs.getString("Online"))){
                        lista = lista + simpDate.format(rs.getDate("DATA"))+" "+rs.getTime("HORA") +"\t"+ String.format("%.2f", rs.getDouble("VALOR")) +"\t\t";
                        lista = lista + "2%\t";
                        lista = lista + String.format("%.2f", rs.getDouble("CASHBACK")) + "\t    " + rs.getString("ONLINE") + "\n";
                    }   
                    else{
                        rs.next(); 
                    }
                }
                areaResultados.setText(lista);
                String s = "Extrato de notas fiscais encontrado!";
                JOptionPane.showMessageDialog(null, s, "Informação: Extrato Carregado.", JOptionPane.INFORMATION_MESSAGE);

            } catch( SQLException e) {
                String s = "Consulta não foi possível " + e.getMessage();
                JOptionPane.showMessageDialog(null, s, "Erro na busca do cliente", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            String s = "Consulta não foi possível, digite um CPF correto.";
            JOptionPane.showMessageDialog(null, s, "Erro na busca do cliente", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExtratoNotasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface_gerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface_gerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface_gerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface_gerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface_gerenciamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaResultados;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExtratoCashback;
    private javax.swing.JButton btnExtratoNotas;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCampo;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblFeicash;
    private javax.swing.JTextField txtCpf;
    // End of variables declaration//GEN-END:variables
}
